# Generated by Django 5.1.1 on 2024-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('report_type', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=9)),
                ('user_comment', models.TextField(blank=True, max_length=150, null=True)),
                ('admin_comment', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('received', 'received'), ('approved', 'approved'), ('completed', 'completed'), ('refused', 'refused')], default='received', max_length=20)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('refused_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
